### ISSUE TITLE
。

### ISSUE THREAD

**Issue by SilasQin** [2331892928/hax_woiden#1]
RT

**Comment by 2331892928** [comment]
woiden.id还是hax.co.id，cookie检测只做了woiden.id，你可以把所有的woiden.id替换成Domain变量，如果你会python的话

**Comment by QJM16** [comment]
感谢回复，我刚是用windows测试的，能移植到Debian上用吗

**Comment by 2331892928** [comment]
> 感谢回复，我刚是用windows测试的，能移植到Debian上用吗

因为基于selenium，所以只要你系统的python支持selenium模块，并且系统是可视化图形就行
